package Access;

import java.io.File;

import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;

public class StringDemos {
	static Logger logger=Logger.getLogger(StringDemos.class);
	public static void main(String[] args) {
		String log4jConfigFile=System.getProperty("user.dir")+File.separator+"log4j.Properties";
		PropertyConfigurator.configure(log4jConfigFile);
		//System.out.println(PropertyConfigurator.configure(log4jConfigFile));
		logger.info(log4jConfigFile);
		logger.info("log4j.Properties");
		logger.info(System.getProperty("user.dir"));
		//int u=10;
		Integer t=Integer.valueOf(20);
		logger.info(t);
		String a="Hello",b="Muthu",c="Hi",g="Muthu";
		boolean s=b.equals(g);
		logger.info(s);
		logger.info(String.valueOf(b.equals(c)));//equal to true or false
		logger.info(b.equals(a));
		
		char d=a.charAt(4);//Location to get Character
		logger.info(d);  
		logger.info(b.charAt(0));
		b.chars();
		logger.info(b.chars());
		
		int e=b.codePointAt(4);
		logger.info(c.codePointAt(1));// get Character ascii value
		logger.info(e);
		
		int f=a.codePointBefore(1);
		logger.info(f);
		logger.info(b.codePointBefore(3));//1,2,3,4 to check value provide ascii value-1
		
		String z=b.valueOf("HI HI");
		logger.info(g);
		logger.info(b);
		
		String h=b.concat(c);
		logger.info(h);
		logger.info(a.concat(h));
		
		b.charAt(2);
		logger.info(b.charAt(2));
		b.chars();
		logger.info(b.chars());
		b.codePointAt(2);
		logger.info(b.codePointAt(2));
		b.codePointBefore(2);
		logger.info(b.codePointBefore(2));
		b.codePointCount(1, 2);
		logger.info(b.codePointCount(1, 4));
		b.codePoints();
		logger.info(b.codePoints());
		b.compareTo(h);
		logger.info(b.compareTo(h));
		b.compareToIgnoreCase(h);
		logger.info(b.compareToIgnoreCase(h));
		b.concat(h);
		logger.info(b.concat(h));
		b.contains(h);
		logger.info(b.contains(h));
		logger.info(h.contains(h));
		b.contentEquals(c);
		logger.info(b.contentEquals(a));
		b.contentEquals("");
		logger.info(b.contentEquals("Muthu"));
		b.describeConstable();
		logger.info(b.describeConstable());
		b.endsWith(h);
		logger.info(b.endsWith(h));
		b.equals(c);
		logger.info(b.equals(c));
		b.equalsIgnoreCase(h);
		logger.info(b.equalsIgnoreCase(h));
		b.formatted(args);
		logger.info(b.formatted(args));
		b.getBytes();
		logger.info(b.getBytes());
		b.getClass();
		logger.info(b.getClass());
		b.hashCode();
		logger.info(b.hashCode());
		b.indent(f);
		logger.info(b.indent(f));
		b.indexOf(f);
		logger.info(b.indexOf(f));
		b.indexOf(h);
		logger.info(b.indexOf(h));
		b.indexOf(e, f);
		logger.info(b.indexOf(e, f));
		b.lastIndexOf(h, f);
		logger.info(b.lastIndexOf(h, f));
		b.length();
		logger.info(b.length());
		b.lines();
		logger.info(b.lines());
		b.matches(g);
		logger.info(b.matches(g));
		b.regionMatches(f, h, f, e);
		logger.info(b.regionMatches(f, h, f, e));
		b.regionMatches(s, f, h, f, e);
		logger.info(b.regionMatches(f, h, f, e));
		b.repeat(f);
		logger.info(b.repeat(f));
		b.replace(d, d);b.replace(g, c);
		logger.info(b.replace(d, d)+b.replace(g, c));
		b.replace(g, c);
		logger.info(b.replace(g, c));
		b.replaceAll(g, c);
		logger.info(b.replaceAll(g, c));
		b.replaceFirst(g, c);
		logger.info(b.replaceFirst(g, c));
		b.resolveConstantDesc(null);
		logger.info(b.resolveConstantDesc(null));
		b.split(g);
		logger.info(b.split(g));
		b.split(g, f);
		logger.info(b.split(g,f));
		b.startsWith(h);
		logger.info(b.startsWith(h));
		b.startsWith(h, f);
		logger.info(b.startsWith(h, f));
		b.strip();
		logger.info(b.strip());
		b.stripIndent();
		logger.info(b.stripIndent());
		b.stripLeading();
		logger.info(b.stripLeading());
		b.stripTrailing();
        logger.info(b.stripTrailing());
		b.toCharArray();
		logger.info(b.toCharArray());
		b.toLowerCase();
		logger.info(b.toLowerCase());
		b.toString();
		logger.info(b.toString());
		b.toUpperCase();
		logger.info(b.toUpperCase());
		b.translateEscapes();
		logger.info(b.translateEscapes());
		b.trim();
		logger.info(b.trim());
		logger.info(b.CASE_INSENSITIVE_ORDER);
		b.format(a, args);
		logger.info(b.format(a, args));
		b.format(null, a, args);
		logger.info(b.format(null, a, args));
		b.join(h, args);
		logger.info(b.join(h, args));
		b.valueOf(b);
		logger.info(b.valueOf(b));
		b.valueOf(f);
		logger.info(b.valueOf(f));
		b.valueOf(f);
		logger.info(b.valueOf(f));
		b.valueOf(f);
		logger.info(b.valueOf(f));
		b.valueOf(d);
		logger.info(b.valueOf(d));
		b.valueOf(d);
		logger.info(b.valueOf(d));
		b.valueOf(s);
		logger.info(b.valueOf(s));
		//b.valueOf(b[2], 1, 1);
	    //logger.warn(b.valueOf(b[2], 1, 1));
		//b.getBytes(null);
		//b.getBytes(h);
		//b.getChars(e, d, null, e);
	   //logger.info(b.getChars(a, c,null , b));
		//b.notify();
		//logger.info(b.notify());
		//b.notifyAll();
		//logger.info(b.notifyAll());
		//b.offsetByCodePoints(e, f);
		//logger.info(b.offsetByCodePoints(e, f));	
		//b.subSequence(d, e);
		//logger.info(b.subSequence(d, e));
		//b.substring(e);
		//logger.info(b.substring(e));
		//b.substring(d, e);
		//logger.info(b.substring(d, e));
		//b.toLowerCase(null);
		//logger.info(b.toLowerCase(null));
		//b.toUpperCase(null);
		//logger.info(b.toUpperCase(null));
		//b.transform(null);
		//logger.info(b.transform(null));
		//b.wait();
		//logger.info(b.wait());
		//b.wait(e);
	    //logger.info(b.wait(e));
		//b.wait(e, f);
		//logger.info(b.wait(e, f));
		//b.CASE_INSENSITIVE_ORDER;
		//b.copyValueOf(null);
		//logger.info(b.copyValueOf(null));
		//b.copyValueOf(null, e, f);
		//logger.info(b.copyValueOf(null, e ,f));
		//b.join(h, null);
		//logger.info(b.join(h, null));
		//b.valueOf(null, e, f);
		//logger.info(b.valueOf(null, e, f));
		//b.valueOf(null);
		//logger.info(b.valueOf(null));
	}
}
